version: 2.1



jobs:
  build:
  
  
    docker:
    
      - image: cimg/openjdk:17.0


    working_directory: ~/CtrAltElite-Java-NextJS-Attendance-Tracker/backend

    environment:
      
      JVM_OPTS: -Xmx3200m
      TERM: dumb
  
  
    steps:
       - checkout:
          path: ~/CtrAltElite-Java-NextJS-Attendance-Tracker
          
          
       - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
          
            - v1-dependencies-

       - run: gradle dependencies

       - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}

      
       - run: gradle test
       
       
       - store_artifacts:
           path: build/test-results/test/binary/
           destination: test-results


       - store_test_results:
           path: build/test-results
